/**
 * Mock data for public / development builds.
 *
 * When Feishu credentials are not configured, the app falls back to
 * these sample entries so the UI can be previewed without connecting
 * to a real backend.
 *
 * Replace with your own Feishu integration in production.
 */
import type { PhotoEntry } from "./types";

const MOCK_ENTRIES: PhotoEntry[] = [
  {
    id: "001",
    title: "胡同口的午后",
    titleEn: "Afternoon at the Hutong Entrance",
    titleJa: "胡同口の午後",
    description: "阳光透过老槐树的枝叶洒在青砖墙上，胡同里传来自行车铃声和孩子的嬉笑声。",
    descEn: "Sunlight filters through the old locust tree, casting shadows on the grey brick walls.",
    descJa: "古い槐の木の枝葉を通して日差しが青煉瓦の壁に降り注ぐ。",
    date: "2026-04-15",
    image: {
      src: "/images/archive/placeholder.jpg",
      width: 1600,
      height: 1200,
      alt: "胡同口的午后",
    },
    location: {
      name: "菊儿胡同",
      district: "东城区",
      coordinates: { lat: 39.9375, lng: 116.4025 },
    },
    locationText: "东城区 菊儿胡同",
    locationEn: "Dongcheng Juer Hutong",
    locationJa: "東城区 菊児胡同",
    tags: ["胡同", "阳光", "生活"],
    weather: { condition: "sunny", temperature: 24, aqi: "良" },
    season: "spring",
    featured: true,
    camera: { model: "Xiaomi 13", settings: "f/1.8 1/1000s" },
  },
  {
    id: "002",
    title: "国贸的黄昏",
    titleEn: "Dusk at Guomao CBD",
    titleJa: "国貿の夕暮れ",
    description: "夕阳照耀在CBD的玻璃幕墙上，城市的天际线在金色的光芒中格外壮观。",
    descEn: "The setting sun glows on the glass facades of the CBD skyline.",
    descJa: "夕日がCBDのガラス張りの壁を照らし、金色に輝く街並み。",
    date: "2026-04-10",
    image: {
      src: "/images/archive/placeholder.jpg",
      width: 1600,
      height: 1200,
      alt: "国贸的黄昏",
    },
    location: {
      name: "国贸",
      district: "朝阳区",
      coordinates: { lat: 39.9087, lng: 116.4605 },
    },
    locationText: "朝阳区 国贸",
    locationEn: "Chaoyang Guomao",
    locationJa: "朝陽区 国貿",
    tags: ["CBD", "日落", "城市"],
    weather: { condition: "sunny", temperature: 20, aqi: "优" },
    season: "spring",
    featured: false,
    camera: { model: "Xiaomi 13", settings: "f/2.0 1/800s" },
  },
  {
    id: "003",
    title: "后海的夜晚",
    titleEn: "Night at Houhai",
    titleJa: "后海の夜",
    description: "酒吧街的霓虹灯倒映在湖面上，远处传来悠扬的民谣歌声。",
    descEn: "Neon lights from the bar street reflect on the lake, with folk music drifting in the distance.",
    descJa: "バー街のネオンが湖面に映り、遠くからフォークソングが聞こえてくる。",
    date: "2026-04-05",
    image: {
      src: "/images/archive/placeholder.jpg",
      width: 1600,
      height: 1200,
      alt: "后海的夜晚",
    },
    location: {
      name: "后海",
      district: "西城区",
      coordinates: { lat: 39.9400, lng: 116.3850 },
    },
    locationText: "西城区 后海",
    locationEn: "Xicheng Houhai",
    locationJa: "西城区 后海",
    tags: ["夜景", "酒吧", "湖"],
    weather: { condition: "sunny", temperature: 15, aqi: "良" },
    season: "spring",
    featured: false,
    camera: { model: "Xiaomi 13", settings: "f/1.8 1/30s ISO 800" },
  },
  {
    id: "004",
    title: "雨后的大学路",
    titleEn: "University Road After Rain",
    titleJa: "雨上がりの大学路",
    description: "一场春雨过后，路面的积水倒映着两侧的法桐和路灯，空气格外清新。",
    descEn: "After a spring rain, puddles mirror the plane trees and street lamps lining the road.",
    descJa: "春の雨が上がり、路面の水たまりが道端のプラタナスと街灯を映し出す。",
    date: "2026-03-28",
    image: {
      src: "/images/archive/placeholder.jpg",
      width: 1600,
      height: 1200,
      alt: "雨后的大学路",
    },
    location: {
      name: "学院路",
      district: "海淀区",
      coordinates: { lat: 39.9835, lng: 116.3390 },
    },
    locationText: "海淀区 学院路",
    locationEn: "Haidian Xueyuan Road",
    locationJa: "海淀区 学院路",
    tags: ["雨后", "倒影", "路"],
    weather: { condition: "rainy", temperature: 12, aqi: "优" },
    season: "spring",
    featured: false,
    camera: { model: "Xiaomi 13", settings: "f/1.8 1/500s" },
  },
  {
    id: "005",
    title: "鼓楼大街",
    titleEn: "Gulou Street",
    titleJa: "鼓楼大街",
    description: "鼓楼在蓝天的映衬下格外庄重，游客们骑着自行车穿梭在古老的街巷中。",
    descEn: "The Drum Tower stands solemn against the blue sky, with cyclists weaving through ancient alleys.",
    descJa: "鼓楼が青空に映え、観光客が自転車で古い街並みを巡る。",
    date: "2026-03-20",
    image: {
      src: "/images/archive/placeholder.jpg",
      width: 1600,
      height: 1200,
      alt: "鼓楼大街",
    },
    location: {
      name: "鼓楼",
      district: "东城区",
      coordinates: { lat: 39.9380, lng: 116.4030 },
    },
    locationText: "东城区 鼓楼",
    locationEn: "Dongcheng Gulou",
    locationJa: "東城区 鼓楼",
    tags: ["古迹", "蓝天", "街景"],
    weather: { condition: "sunny", temperature: 18, aqi: "优" },
    season: "spring",
    featured: false,
    camera: { model: "Xiaomi 13", settings: "f/2.2 1/1200s" },
  },
];

export default MOCK_ENTRIES;
